import { useRouter } from 'next/router';
import Head from 'next/head';

export default function PageHead() {
	const router = useRouter();
	const query = router.query;
	console.log(query);

	return (
		<Head>
			<title>Lifeway IT | Tico Thepsourinthone</title>
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.ico' />
		</Head>
	);
}
