import Head from 'next/head';
import getPageRouteStr from '../utils/getPageRouteStr.js';

export default function PageHead() {
	return (
		<Head>
			<title>StarWarsMnG | {getPageRouteStr() || 'Hardcoded Page Route'}</title>
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.ico' />
		</Head>
	);
}
