import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Button } from '@nextui-org/react';
import styles from '../styles/HomePage.module.css';

export default function HomePage() {
	const CharactersButton = () => (
		<Button color='gradient' size='xl' ghost>
			Characters
		</Button>
	);

	return (
		<div className={styles.container}>
			<Head>
				<title>Lifeway IT | Tico Thepsourinthone</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Welcome to Star Wars Meet & Greet!</h1>
				<div className={styles.container}>
					<img
						className={styles.heroImage}
						src='../images/hero_image.jpg'
						alt='Darth Vader coffee meme'
					/>
					<h2>
						Your one-stop-shop for learning all about your favorite Star Wars
						characters and more!
					</h2>
					<Link href='/characters'>{CharactersButton()}</Link>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
