import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function HomePage() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Lifeway IT | Tico Thepsourinthone</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Star Wars Meet & Greet</h1>
				<div>
					<h2>
						Welcome to your one-stop-shop for learning all about your favorite
						Star Wars characters and more!
					</h2>
				</div>
				<div className={styles.cardContainer}>
					<Link href='/characters'>
						<h2 className={styles.card}>Characters List</h2>
					</Link>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
